FROM node:20.19.6-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

RUN mkdir -p data

COPY src ./src

EXPOSE 3000

COPY ./tools/start.sh /tools/start.sh

RUN chmod 700 /tools/start.sh

CMD ["/tools/start.sh"]
