services:
  nginx_front:
    container_name: nginx_front
    build:
      context: ./containers/nginx_front
      dockerfile: Dockerfile.prod
    ports:
      - "8080:443"
    depends_on:
      - api_gateway
    networks:
      - front
    restart: always
    volumes:
      - certs_volume:/certs:ro

  api_gateway:
    build:
      dockerfile: Dockerfile.prod