services:
   nginx_front:
    container_name: nginx_front
    build:
      context: ./containers/nginx_front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - api_gateway
    networks:
      - front
    restart: always
    volumes:
      - ./containers/nginx_front/front-end:/app # bind mount, no aparece  en "docker volume ls" a no ser que lo declaremos como en inception imagino
      - /app/node_modules # volumen anonimo
      - certs_volume:/certs:ro

   user-service:
    build:
      dockerfile: Dockerfile.dev 
    volumes:
      - ./containers/user/user-service:/app
      - /app/node_modules

   auth-service:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/auth:/app
      - /app/node_modules

   api_gateway:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/api_gateway:/app
      - /app/node_modules