FROM node:20.19.6-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm ci

# Nodemon needs file system events
# this one makes sure nodemon uses polls, which is necessary with alpine
ENV CHOKIDAR_USEPOLLING=true

COPY ./tools/dev-start.sh /tools/dev-start.sh

RUN chmod 700 /tools/dev-start.sh

EXPOSE 3000

CMD ["/tools/dev-start.sh"]