FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

COPY ./tools/dev-start.sh /tools/dev-start.sh

RUN chmod 700 /tools/dev-start.sh

CMD ["/tools/dev-start.sh"]